-- PROJET 1
-- SUJET:
-- Créer un jeu snake simplifié
-- 	- R2D2 doit bouger avec les fleches du clavier
--	- Des piles electriques sont placees aleatoirement sur la zone de jeu
--	- R2D2 doit recuperer les piles en roulant dessusa !
--	- Quand R2D2 recupere une pile, une nouvelle est placee aleatoirement
--	- Un nombre affiche en haut de l'ecran le nombre de piles recuperees
--	
-- BONUS:
-- 	- Faites quitter le jeu en appuyant sur echap
--	- Empecher r2d2 de quitter la fenetre
--	- AJoutez une couleur de fond !
-- BONUS HARDCORE:
--	- Ajoutez des ennemis
--	- Cliquer pour tirer sur un ennemi !
--	- Tout ce que vous pouvez imaginer
-- Regardez les exercices precedents ;)

-- indice: https://love2d.org/wiki/love.math.random
